name: Publish

on:
  push:
    branches: ['main']

permissions:
    contents: read
    packages: write

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - uses: actions/checkout@v3

      - uses: ko-build/setup-ko@v0.6
      - run: |
            tag=$(echo ${{ github.ref }} | cut -c11-)  # get tag name without tags/refs/ prefix.
            ko build -B